name: Add-Providers

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
    # inputs:
      # tag:
      #   type: string
      #   description: Tag version of published docker image.
      #   required: true

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Terraform
        run: |
          # install terraform
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
          sudo curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install terraform=1.6.5-1

          terraform init

          cp -r -v -n .terraform/providers/registry.terraform.io ./terraform-providers
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Add providers"
          git push
